[package]
name = "meow-snapshot"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
meow-runtime = { path = "../runtime" }
meow-pkg = { path = "../pkg" }
meow-loader = { path = "../loader" }

# Deno extensions with the same features as the runtime
deno_node = { path = "../../vendor/deno_node" }
deno_core = { workspace = true }
deno_webidl = { workspace = true }
deno_web = { workspace = true }
deno_crypto = { workspace = true }
deno_fetch = { workspace = true }
deno_net = { workspace = true }
