[package]
name = "meow-lsp"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
meow-loader = { path = "../loader" }
meow-pkg = { path = "../pkg" }
meow-runtime = { path = "../runtime", default-features = false }
thiserror = { workspace = true }
deno_core = { workspace = true }

[dev-dependencies]
meow-graph = { path = "../graph" }
meow-runtime = { path = "../runtime" }
flate2 = { workspace = true }
tar = { workspace = true }
tokio = { workspace = true }
