//! Root `package.json` projection (CFG-002 · ADR-8, §18.1).
//!
//! `package.json` has no `extends` mechanism, so the tsconfig shim trick cannot
//! apply: `meow` instead generates the **real** root `package.json` as a derived
//! artifact and OWNS/overwrites it. Publishing metadata (`name`/`version`/
//! `exports`/…) is a **projection** of the single human-edited `meow.config.ts`
//! (`publish: {...}`), never a second authority the ecosystem edits independently
//! (I-1). The file is byte-stable, carries a provenance marker, and hand-edits are
//! detected rather than silently merged (I-9).
//!
//! Field order is fixed by the [`RootPackageJson`] struct's declaration order —
//! serde serializes struct fields in order, so the output is byte-stable WITHOUT
//! `serde_json/preserve_order` (which would reorder PKG's lockfile too).

use crate::{ConfigError, MeowConfig};
use serde::Serialize;
use std::collections::BTreeMap;
use std::path::Path;

/// Provenance marker. `package.json` is strict JSON (no comments), so the marker
/// rides in the npm-blessed `"//"` comment key — the only place a marker is valid.
/// Byte-stable sentinel: regeneration always emits this exact string.
pub const PACKAGE_JSON_MARKER: &str =
    "GENERATED by `meow sync` from meow.config.ts — edits are clobbered (ADR-8).";

/// The projected shape, in emission order (serde serializes fields top-to-bottom).
/// `type` is fixed to `"module"` (first-party is ESM-only, I-2); the rest project
/// from `cfg.publish`, omitting absent optionals so the file is never half-baked.
#[derive(Serialize)]
struct RootPackageJson {
    #[serde(rename = "//")]
    marker: &'static str,
    #[serde(skip_serializing_if = "Option::is_none")]
    name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    version: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    description: Option<String>,
    #[serde(rename = "type")]
    package_type: &'static str,
    #[serde(skip_serializing_if = "Option::is_none")]
    license: Option<String>,
    #[serde(skip_serializing_if = "is_false")]
    private: bool,
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    exports: BTreeMap<String, String>,
}

fn is_false(b: &bool) -> bool {
    !*b
}

/// Project `cfg.publish` into the exact bytes of the root `package.json`. Pure, no
/// I/O. Deterministic / byte-stable: identical `cfg` ⇒ identical bytes (fixed field
/// order, `BTreeMap` exports, pretty-print, single trailing newline).
pub fn render_root_package_json(cfg: &MeowConfig) -> String {
    let p = &cfg.publish;
    let root = RootPackageJson {
        marker: PACKAGE_JSON_MARKER,
        name: p.name.clone(),
        version: p.version.clone(),
        description: p.description.clone(),
        // First-party is ESM-only (I-2); `type` is not configurable.
        package_type: "module",
        license: p.license.clone(),
        private: p.private,
        exports: p.exports.clone(),
    };
    // `to_string_pretty` cannot fail on this fully-owned, finite value.
    let mut out = serde_json::to_string_pretty(&root).unwrap_or_default();
    out.push('\n');
    out
}

/// Regenerate `root/package.json` from `cfg`, OWNING/overwriting it (ADR-8). Skips
/// the write when on-disk bytes already match (mtime-stable / idempotent, I-9).
pub fn generate_root_package_json(cfg: &MeowConfig, root: &Path) -> Result<(), ConfigError> {
    let path = root.join("package.json");
    let contents = render_root_package_json(cfg);
    if let Ok(existing) = std::fs::read(&path) {
        if existing == contents.as_bytes() {
            return Ok(());
        }
    }
    std::fs::write(&path, contents).map_err(|source| ConfigError::Io {
        action: "write",
        path,
        source,
    })
}

/// Provenance/staleness of the on-disk root `package.json` vs the projection. The
/// `meow doctor` package.json check (the only doctor surface CFG-002 owns).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PackageJsonStatus {
    /// No root `package.json` yet — `meow sync` will create it.
    Missing,
    /// Byte-identical to the projection — in sync.
    Fresh,
    /// Carries the meow marker but differs (config moved on since the last sync).
    /// `meow sync` regenerates; not a hand-edit.
    Stale,
    /// Differs AND lacks the meow marker — hand-written/edited. `meow sync` WILL
    /// overwrite it (ADR-8 honest boundary).
    HandEdited,
}

/// Classify `root/package.json` against the projection of `cfg`. Read-only. An
/// unparseable on-disk file is `HandEdited` (it differs and carries no valid
/// marker), never a hard error — so `doctor` warns instead of aborting.
pub fn classify_root_package_json(
    cfg: &MeowConfig,
    root: &Path,
) -> Result<PackageJsonStatus, ConfigError> {
    let path = root.join("package.json");
    let existing = match std::fs::read(&path) {
        Ok(bytes) => bytes,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            return Ok(PackageJsonStatus::Missing)
        }
        Err(source) => {
            return Err(ConfigError::Io {
                action: "read",
                path,
                source,
            })
        }
    };
    if existing == render_root_package_json(cfg).as_bytes() {
        return Ok(PackageJsonStatus::Fresh);
    }
    let marker_present = serde_json::from_slice::<serde_json::Value>(&existing)
        .ok()
        .and_then(|v| {
            v.get("//")
                .and_then(|m| m.as_str())
                .map(|s| s == PACKAGE_JSON_MARKER)
        })
        .unwrap_or(false);
    Ok(if marker_present {
        PackageJsonStatus::Stale
    } else {
        PackageJsonStatus::HandEdited
    })
}
