[package]
name = "meow-tool"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
meow-graph = { path = "../graph" }
thiserror = { workspace = true }
oxc_codegen = { workspace = true }
oxc_diagnostics = { workspace = true }
